---
layout: post
title: 异常
date: 2021-04-19
Author: yufeng 
tags: [Java]
comments: true
toc: true
---

## 异常

基本异常是指阻止当前方法或作用域继续执行得问题，要区分异常情形和普通问题。所谓的普通问题是指，在当前环境下能得到足够的信息，总能处理这个错误。而对于异常情形，就不能继续下去了，因为在当前环境下无法获得必要的信息来解决问题。你所能做的就是从当前环境跳出，并且把问题提交给上一级环境。这就是抛出异常时所发生的事情。

![img](https://camo.githubusercontent.com/17d2b543fcd5c80208deea27d941b41d7cb868da7172d6cf1e91722b34a86f0b/68747470733a2f2f67756964652d626c6f672d696d616765732e6f73732d636e2d7368656e7a68656e2e616c6979756e63732e636f6d2f323032302d31322f4a617661254535254243253832254535254238254238254537254231254242254535254231253832254536254143254131254537254242253933254536253945253834254535253942254245322e706e67)

#### 常见的Error和Exception

FileNotFoundException，ClassNotFoundException，NullPointerException和IndexOutOfBoundException，ClassCastException（JVM在检测到两个类型间转换不兼容时引发的运行时异常。）

#### 异常捕获

```java
try {
    // Code that might generate exceptions
} catch(Type1 id1) {
    // Handle exceptions of Type1
} catch(Type2 id2) {
    // Handle exceptions of Type2
} catch(Type3 id3) {
    // Handle exceptions of Type3
}
// etc.
```

有了异常处理机制，可以把所有动作都放在 try 块里，然后只需在一个地方就可以捕获所有异常。

当异常被抛出时，异常处理机制将负责搜寻参数与异常类型相匹配的第一个处理程序。然后进入 catch 子句执行，此时认为异常得到了处理。一旦 catch 子句结束，则处理程序的查找过程结束。

#### 自定义异常

可以自己自定义异常类，从已有得异常类继承。

```java
class SimpleException extends Exception {}

public class InheritingExceptions {
    public void f() throws SimpleException {
        System.out.println(
                "Throw SimpleException from f()");
        throw new SimpleException();
    }
    public static void main(String[] args) {
        InheritingExceptions sed =
                new InheritingExceptions();
        try {
            sed.f();
        } catch(SimpleException e) {
            System.out.println("Caught it!");
        }
    }
}
```

#### 异常与记录日志

可使用java.util.logging工具将输出记录到日志中。

```java
import java.util.logging.*;
import java.io.*;
public class LoggingExceptions2 {
    private static Logger logger =
            Logger.getLogger("LoggingExceptions2");
    static void logException(Exception e) {
        StringWriter trace = new StringWriter();
        e.printStackTrace(new PrintWriter(trace));
        logger.severe(trace.toString());
    }
    public static void main(String[] args) {
        try {
            throw new NullPointerException();
        } catch(NullPointerException e) {
            logException(e);
        }
    }
}
```

#### Java标准异常

Throwable 这个 Java 类被用来表示任何可以作为异常被抛出的类。Throwable 对象可分为两种类型（指从 Throwable 继承而得到的类型）：Error 用来表示编译时和系统错误（除特殊情况外，一般不用你关心）；Exception 是可以被抛出的基本类型，在 Java 类库、用户方法以及运行时故障中都可能抛出 Exception 型异常。所以 Java 程序员关心的基类型通常是 Exception。

如果受检查异常没有被 `catch`/`throw` 处理的话，就没办法通过编译 ；除了RuntimeException及其子类以外，其他的Exception类及其子类都属于受检查异常。

#### 使用finally进行清理

希望无论try块中得异常是否抛出，都要得到执行。

```java
try {
// The guarded region: Dangerous activities
// that might throw A, B, or C
} catch(A a1) {
// Handler for situation A
} catch(B b1) {
// Handler for situation B
} catch(C c1) {
// Handler for situation C
} finally {
// Activities that happen every time
}
```

当要把除内存之外得资源恢复到它们得初始状态时，可以使用finally子句。

以下三种情况下finally不会被执行：

1. 在 `try` 或 `finally`块中用了 `System.exit(int)`退出程序。但是，如果 `System.exit(int)` 在异常语句之后，`finally` 还是会被执行
2. 程序所在的线程死亡。
3. 关闭 CPU。

#### 缺憾：异常丢失

Java异常实现有瑕疵，异常有可能被轻易地忽略

```java
// exceptions/LostMessage.java
// How an exception can be lost
class VeryImportantException extends Exception {
    @Override
    public String toString() {
        return "A very important exception!";
    }
}
class HoHumException extends Exception {
    @Override
    public String toString() {
        return "A trivial exception";
    }
}
public class LostMessage {
    void f() throws VeryImportantException {
        throw new VeryImportantException();
    }
    void dispose() throws HoHumException {
        throw new HoHumException();
    }
    public static void main(String[] args) {
        try {
            LostMessage lm = new LostMessage();
            try {
                lm.f();
            } finally {
                lm.dispose();
            }
        } catch(VeryImportantException | HoHumException e) {
            System.out.println(e);
        }
    }
}
```

#### try-with-resources用法

```java
import java.io.*;
public class TryWithResources {
    public static void main(String[] args) {
        Scanner sc = null;
        try(
            sc = new Scanner(new File("./read.txt"));
            while(sc.hasNext()) System.out.println(sc.nextLine());
        ) catch (FileNotFoundException e) {
            e.printStackTrace();
        } finally {
            if(sc != null) sc.close();
        }
    }
    public static void resource() {
        try(Scanner sc = new Scanner(new File("test.txt"))) {
            while(sc.hasNext()) System.out.println(sc.nextLine());
        } catch(FileNotFoundException e) {
            e.printStackTrace();
        }
    }
    
    // 多个资源需要关闭
    try (BufferedInputStream bin = new BufferedInputStream(new FileInputStream(new File("test.txt")));
             BufferedOutputStream bout = new BufferedOutputStream(new FileOutputStream(new File("out.txt")))) {
            int b;
            while ((b = bin.read()) != -1) {
                bout.write(b);
            }
        }
        catch (IOException e) {
            e.printStackTrace();
        }
}
```

在 Java 7 之前，try 后面总是跟着一个 {，但是现在可以跟一个带括号的定义 ——这里是我们创建的 FileInputStream 对象。括号内的部分称为资源规范头（resource specification header）。现在 `in` 在整个 try 块的其余部分都是可用的。try-with-resources定义子句中创建的对象必须实现java.lang.AutoCloseable或Java.io.Closeable接口，退出try会调用它的close()方法。

面对必须要关闭的资源，我们总是应该优先使用 `try-with-resources` 而不是`try-finally`。随之产生的代码更简短，更清晰，产生的异常对我们也更有用。`try-with-resources`语句让我们更容易编写必须要关闭的资源的代码，若采用`try-finally`则几乎做不到这点。

#### 异常匹配

抛出异常时，异常处理系统按照代码得书写顺序找出最近得处理程序，当找到后，则不再继续查找。查找的时候并不要求抛出的异常同处理程序所声明的异常完全匹配。
